import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PublicNavbar from "@/components/PublicNavbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable}`}
    >
      
      <body className="">
        
        <main className="w-full bg-surface-low">      
          <PublicNavbar />
        
        </main>
        {children}


      </body>
    </html>
  );
}
